/*
Copyright 2018 Heptio Inc.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

package app

import (
	"os"
	"time"

	"github.com/heptio/sonobuoy/pkg/client"
	"github.com/heptio/sonobuoy/pkg/errlog"
	"github.com/pkg/errors"
	"github.com/spf13/cobra"
)

var deleteopts client.DeleteConfig

var deleteFlags struct {
	kubeconfig Kubeconfig
	rbacMode   RBACMode
	wait       int
}

func NewCmdDelete() *cobra.Command {
	cmd := &cobra.Command{
		Use:   "delete",
		Short: "Deletes Kubernetes resources that were generated by a Sonobuoy run",
		Run:   deleteSonobuoyRun,
		Args:  cobra.ExactArgs(0),
	}

	AddKubeconfigFlag(&deleteFlags.kubeconfig, cmd.Flags())
	AddNamespaceFlag(&deleteopts.Namespace, cmd.Flags())
	AddRBACModeFlags(&deleteFlags.rbacMode, cmd.Flags(), DetectRBACMode)
	AddDeleteAllFlag(&deleteopts.DeleteAll, cmd.Flags())
	AddDeleteWaitFlag(&deleteFlags.wait, cmd.Flags())

	return cmd
}

func deleteSonobuoyRun(cmd *cobra.Command, args []string) {
	cfg, err := deleteFlags.kubeconfig.Get()
	if err != nil {
		errlog.LogError(errors.Wrap(err, "couldn't get kubernetes config"))
		os.Exit(1)
	}

	sbc, err := getSonobuoyClient(cfg)
	if err != nil {
		errlog.LogError(errors.Wrap(err, "could not create sonobuoy client"))
		os.Exit(1)
	}

	client, err := sbc.Client()
	if err != nil {
		errlog.LogError(err)
		os.Exit(1)
	}

	rbacEnabled, err := deleteFlags.rbacMode.Enabled(client)
	if err != nil {
		errlog.LogError(errors.Wrap(err, "couldn't detect RBAC status"))
		os.Exit(1)
	}
	deleteopts.EnableRBAC = rbacEnabled
	deleteopts.Wait = time.Duration(deleteFlags.wait) * time.Minute

	if err := sbc.Delete(&deleteopts); err != nil {
		errlog.LogError(errors.Wrap(err, "failed to delete sonobuoy resources"))
		os.Exit(1)
	}

}
