FROM golang:1.12.1-stretch

RUN go get github.com/estesp/manifest-tool
RUN curl https://sdk.cloud.google.com | bash /dev/stdin --disable-prompts;
RUN echo "export PATH=$PATH:/root/google-cloud-sdk/bin" > $HOME/.bashrc && . $HOME/.bashrc
