kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
- role: control-plane
  image: &kind_node_image kindest/node:v1.26.0
- role: worker
  image: *kind_node_image
- role: worker
  image: *kind_node_image
